# docker-compose.yml

version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - ollama
    # --- MODIFIED: Added the header to skip the browser warning ---
    command: http ollama:11434 --log=stdout --request-header-add "ngrok-skip-browser-warning:true"
    ports:
      - "4040:4040"

  test-runner:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
