# docker-compose.yml

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    # Set the entrypoint to the shell
    entrypoint: /bin/sh
    # Provide the script to the shell
    command:
      - -c
      - |
        ollama serve &
        PID=$$!
        ollama pull $${OLLAMA_MODEL_NAME:-gemma:2b}
        wait $$PID
    environment:
      - OLLAMA_MODEL_NAME
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434"]
      interval: 10s
      timeout: 10s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      ollama:
        condition: service_healthy
    command: http ollama:11434 --log=stdout --request-header-add "ngrok-skip-browser-warning:true"
    ports:
      - "4040:4040"

  test-runner:
    build: .
    command: tail -f /dev/null