# docker-compose.yml

services:
  ollama:
    # Build our custom image instead of pulling from Docker Hub
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    # The default command 'ollama serve' is now sufficient
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434"]
      interval: 10s
      timeout: 10s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      ollama:
        condition: service_healthy
    command: http ollama:11434 --log=stdout --request-header-add "ngrok-skip-browser-warning:true"
    ports:
      - "4040:4040"

  test-runner:
    build: .
    command: tail -f /dev/null