# docker-compose.yml

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    entrypoint: /bin/sh
    command:
      - -c
      - |
        ollama serve &
        PID=$$!
        # This will pull the model specified by the CI workflow
        ollama pull $$OLLAMA_MODEL_NAME
        wait $$PID
    environment:
      # This variable must be passed in from the CI workflow
      - OLLAMA_MODEL_NAME
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434"]
      interval: 10s
      timeout: 10s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      ollama:
        condition: service_healthy
    command: http ollama:11434 --log=stdout --request-header-add "ngrok-skip-browser-warning:true"
    ports:
      - "4040:4040"

  test-runner:
    build: .
    command: tail -f /dev/null