# docker-compose.yml

version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    entrypoint: /bin/bash
    # --- MODIFIED: Use environment variable OLLAMA_MODEL_NAME with a fallback ---
    command: -c "ollama pull ${OLLAMA_MODEL_NAME:-gemma:2b} && ollama serve"
    environment:
      - OLLAMA_MODEL_NAME # Declare that this service expects this environment variable
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434"]
      interval: 10s
      timeout: 10s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      ollama:
        condition: service_healthy
    command: http ollama:11434 --log=stdout --request-header-add "ngrok-skip-browser-warning:true"
    ports:
      - "4040:4040"

  test-runner:
    build: .
    command: tail -f /dev/null