# docker-compose.yml

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    entrypoint: /bin/sh
    command:
      - -c
      - |
        # Start the server in the background
        ollama serve &
        PID=$$!
        
        # Wait for the server to be ready before proceeding
        echo "Waiting for Ollama server to be ready..."
        while ! curl -s -f http://localhost:11434 > /dev/null
        do
          sleep 1
        done
        echo "Ollama server is ready."

        # Now that the server is ready, pull the model
        ollama pull $$OLLAMA_MODEL_NAME
        
        # Wait for the background server process to finish
        wait $$PID
    environment:
      - OLLAMA_MODEL_NAME
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434"]
      interval: 10s
      timeout: 10s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      ollama:
        condition: service_healthy
    command: http ollama:11434 --log=stdout --request-header-add "ngrok-skip-browser-warning:true"
    ports:
      - "4040:4040"

  test-runner:
    build: .
    command: tail -f /dev/null