name = "chronoweave-worker"
main = "src/index.js"
compatibility_date = "2025-06-29"

[[d1_databases]]
binding = "D1"
database_id = "cb6d437a-5098-4f9b-8efc-a86d8217c1fb"

[[kv_namespaces]]
binding = "CHRONOWEAVE_KV"
id = "1710c24dd4684d19a5ebad647f7bd29f"

[[r2_buckets]]
binding = "CHRONOWEAVE_R2"
bucket_name = "chronoweave-r2"
