# .github/workflows/main.yml

name: Reviviscere Engine CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ 'agents/watchtower' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies for ${{ matrix.project }}
        run: npm --prefix ./${{ matrix.project }} install

      # --- MODIFIED: Use npx to run the test command ---
      # This is the standard and more reliable way to execute package binaries in CI.
      - name: Run tests for ${{ matrix.project }}
        run: npx vitest run --root ./${{ matrix.project }}
