# .github/workflows/main.yml

name: Reviviscere Engine CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This job identifies which agent has changed
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      # An output variable will be true if the watchtower code changed
      watchtower: ${{ steps.filter.outputs.watchtower }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            watchtower:
              - 'agents/watchtower/**'

  e2e-test:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    # This job now depends on the 'changes' job
    needs: changes
    # And it only runs if the watchtower code has actually changed
    if: needs.changes.outputs.watchtower == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose environment
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Extract ngrok Tunnel URL
        run: echo "NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')" >> $GITHUB_ENV

      - name: Display ngrok URL
        run: echo "Tunnel is live at ${{ env.NGROK_URL }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Preview and capture URL
        id: deploy_preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          output=$(wrangler deploy --config ./agents/watchtower/wrangler.toml --var WATCHTOWER_MODEL_URL:${{ env.NGROK_URL }} --outdir=dist-preview)
          echo "worker_url=$(echo "$output" | grep -o 'https://[^ ]*workers.dev')" >> $GITHUB_OUTPUT

      - name: Install Watchtower test dependencies
        run: npm --prefix ./agents/watchtower install

      - name: Run Vitest E2E tests against Preview
        env:
          BASE_URL: ${{ steps.deploy_preview.outputs.worker_url }}
          API_KEY: ${{ secrets.API_KEY }}
        run: npx vitest run --root ./agents/watchtower

      - name: Teardown Docker Compose environment
        if: always()
        run: docker compose down
  
  deploy:
    name: Deploy Watchtower to Production
    runs-on: ubuntu-latest
    # This job now depends on both 'changes' and 'e2e-test'
    needs: [changes, e2e-test]
    # It only runs on a push to main, and only if the watchtower code changed
    if: github.ref == 'refs/heads/main' && needs.changes.outputs.watchtower == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This is the corrected, syntactically valid deployment step
      - name: Deploy Watchtower Agent
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --config ./agents/watchtower/wrangler.toml
