# .github/workflows/main.yml

name: Reviviscere Engine CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose environment
        env:
          OLLAMA_MODEL_NAME: tinyllama
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: docker compose up -d --wait

      - name: Show Docker Compose logs on failure
        if: failure()
        run: docker compose logs

      - name: Extract ngrok Tunnel URL
        id: get_url
        run: echo "NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')" >> $GITHUB_OUTPUT

      - name: Display ngrok URL
        run: echo "Tunnel is live at ${{ steps.get_url.outputs.NGROK_URL }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm --prefix ./agents/watchtower ci
          npm install -g wrangler

      - name: Deploy to Cloudflare Preview and Capture Output
        run: wrangler deploy --config ./agents/watchtower/wrangler.toml --var WATCHTOWER_MODEL_URL:${{ steps.get_url.outputs.NGROK_URL }} > deployment-output.txt
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run Vitest E2E tests against Preview
        working-directory: ./agents/watchtower
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CI: true
        run: |
          # Extract the URL from the output file (which is two directories up)
          export BASE_URL=$(grep -o 'https://[^ ]*workers.dev' ../../deployment-output.txt | tr -d '\r')
          
          # Add a final confirmation log
          echo "BASE_URL has been exported as: $BASE_URL"

          # Run the simple npm test script, which will inherit the exported variable
          npm test

      - name: Teardown Docker Compose environment
        if: always()
        run: docker compose down
  
  deploy-production:
    name: Deploy Watchtower to Production
    runs-on: ubuntu-latest
    needs: e2e-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Watchtower Agent
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --config ./agents/watchtower/wrangler.toml